# Generated by Django 5.0.6 on 2025-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_login_name_remove_login_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='phoneno',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
