# Generated by Django 5.0.6 on 2025-05-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_login_name_login_phoneno_alter_login_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='phoneno',
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
