# Generated by Django 5.0.6 on 2025-05-27 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_buyproduct_product_remove_buyproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
