# Generated by Django 5.0.6 on 2025-05-27 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_buyproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='user',
        ),
    ]
