# Generated by Django 5.0.6 on 2025-05-27 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_buyproduct_address_remove_buyproduct_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
            preserve_default=False,
        ),
    ]
