# Generated by Django 5.0.6 on 2025-05-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_buyproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='product',
        ),
    ]
